### Data Collection

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/content/diabetes.csv")

In [5]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

### Data Understanding

In [6]:
data.shape

(768, 9)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [8]:
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [11]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [12]:
import plotly.express as px

In [16]:
fig = px.histogram(
    data,
    x="Pregnancies",
    color="Outcome",
    title = "Pregnancies Vs diabetes"

)

fig.show()

In [21]:
fig = px.scatter(
    data,
    x="Age",
    y="BMI",
    color="Outcome",
    title = "Age Vs Glucose"

)

fig.show()

### Data Preparation

In [22]:
### Quite Clean Dataset

### Data Modelling

In [24]:
# Independent variables
X = data.drop("Outcome",axis=1)



# Dependent variable
y = data["Outcome"]

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [32]:
from sklearn.svm import SVC

In [35]:
svm_model = SVC()

In [38]:
svm_model.fit(X_train,y_train)

SVC()

In [39]:
y_pred = svm_model.predict(X_test)

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(y_test,y_pred)

0.7662337662337663

In [42]:
### SVM with Liner Kernel

svm_linear_model = SVC(kernel="linear")

In [44]:
svm_linear_model.fit(X_train,y_train)

SVC(kernel='linear')

In [45]:
y_pred_linear = svm_linear_model.predict(X_test)

In [46]:
accuracy_score(y_test,y_pred_linear)

0.7532467532467533

In [47]:
### svm with rbf kernel

In [50]:
svm_rbf_model = SVC(kernel="rbf")

In [51]:
svm_rbf_model.fit(X_train,y_train)

SVC()

In [52]:
y_pred_rbf = svm_rbf_model.predict(X_test)

In [53]:
accuracy_score(y_test,y_pred_rbf)

0.7662337662337663

In [ ]:
### svm with polynomial kernel

In [54]:
svm_poly_model = SVC(kernel="poly")

In [55]:
svm_poly_model.fit(X_train,y_train)

SVC(kernel='poly')

In [56]:
y_pred_poly = svm_poly_model.predict(X_test)

In [57]:
accuracy_score(y_test,y_pred_poly)

0.7597402597402597

In [66]:
print("Summary of the Model Experiment SVM:\n\n",


    "SVM Default Model:",round(accuracy_score(y_test,y_pred),4),"%\n",
    "SVM Linear Model:",round(accuracy_score(y_test,y_pred_linear),4),"%\n",
    "SVM RBF Model:",round(accuracy_score(y_test,y_pred_rbf),4),"%\n",
    "SVM Poly Model:",round(accuracy_score(y_test,y_pred_poly),4),"%"


)

Summary of the Model Experiment SVM:

 SVM Default Model: 0.7662 %
 SVM Linear Model: 0.7532 %
 SVM RBF Model: 0.7662 %
 SVM Poly Model: 0.7597 %